// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCLI5-67GfyNfsD3lIwx9Ddaj1lsAKung',
    appId: '1:44435135768:web:347e4396419b812315d26d',
    messagingSenderId: '44435135768',
    projectId: 'moviehub-app-23209',
    authDomain: 'moviehub-app-23209.firebaseapp.com',
    storageBucket: 'moviehub-app-23209.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKIa5joRV-CcrkwJWMGtUJi178uS9LqE',
    appId: '1:44435135768:android:d6e0d6e64335751715d26d',
    messagingSenderId: '44435135768',
    projectId: 'moviehub-app-23209',
    storageBucket: 'moviehub-app-23209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ75hvo70miqw3KVqC1Z1JhvqrBPv4Jw8',
    appId: '1:44435135768:ios:7a7d6ceb67671c4b15d26d',
    messagingSenderId: '44435135768',
    projectId: 'moviehub-app-23209',
    storageBucket: 'moviehub-app-23209.firebasestorage.app',
    iosBundleId: 'com.example.flutter6thassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ75hvo70miqw3KVqC1Z1JhvqrBPv4Jw8',
    appId: '1:44435135768:ios:7a7d6ceb67671c4b15d26d',
    messagingSenderId: '44435135768',
    projectId: 'moviehub-app-23209',
    storageBucket: 'moviehub-app-23209.firebasestorage.app',
    iosBundleId: 'com.example.flutter6thassignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCLI5-67GfyNfsD3lIwx9Ddaj1lsAKung',
    appId: '1:44435135768:web:fe645bbdc468aa4115d26d',
    messagingSenderId: '44435135768',
    projectId: 'moviehub-app-23209',
    authDomain: 'moviehub-app-23209.firebaseapp.com',
    storageBucket: 'moviehub-app-23209.firebasestorage.app',
  );
}
